# docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./orcus
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_EVENT_REGISTRY_API_KEY=${REACT_APP_EVENT_REGISTRY_API_KEY}
    volumes:
      - ./orcus/.env:/app/.env

  backend:
    build:
      context: ./orcus-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./orcus-backend/.env:/app/.env

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
